name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update packages
      run: sudo apt update && sudo apt upgrade
    - name: Install Packages
      run: sudo apt install git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison
    - name: Config
      run: make defconfig
    - run: echo 'CONFIG_SYSTEM_TRUSTED_KEYS = ""' >>.config
    - name: Make
      run: make -j "$(nproc)" bindeb-pkg
    - name: Save image
      uses: actions/upload-artifact@v3
      with:
          name: image
          path: |
            *.deb
